services:
    form.type.textangular:
        class: Chaplean\Bundle\CmsBundle\Form\Type\TextAngularType
        tags:
            - { name: form.type, alias: textAngular }

    chaplean_cms.cms_extension:
        class: Chaplean\Bundle\CmsBundle\Twig\Extension\CmsExtension
        arguments: [%chaplean_cms%]
        tags:
            - { name: 'twig.extension' }
    app.tokens.action_listener:
        class: Chaplean\Bundle\CmsBundle\Utility\ConfigListener
        arguments: [%chaplean_cms%]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
