Chaplean\Bundle\CmsBundle\Entity\Page:
    properties:
        title:
            - NotBlank:
                message: general.not_blank
                groups: ['edit_page']

Chaplean\Bundle\CmsBundle\Entity\PageRoute:
    properties:
        path:
            - NotBlank:
                message: general.not_blank
                groups: ['edit_page']
        menuName:
            - NotBlank:
                message: general.not_blank
                groups: ['edit_page']
        page:
            - NotBlank:
                message: general.not_blank
                groups: ['edit_page']
            - Type:
                type: object
                message: general.not_blank
                groups: ['edit_page']

Chaplean\Bundle\CmsBundle\Entity\Publication:
    properties:
        status:
            - NotBlank:
                message: general.not_blank

Chaplean\Bundle\CmsBundle\Entity\Block:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank:
                message: general.not_blank

Chaplean\Bundle\CmsBundle\Entity\Media:
    properties:
        path:
            - NotBlank:
                message: general.not_blank
                groups: ['default']
        fileName:
            - NotBlank:
                message: general.not_blank
                groups: ['default']
        fileWeight:
            - NotBlank:
                message: general.not_blank
                groups: ['default']
        isPublic:
            - NotBlank:
                message: general.not_blank
                groups: ['default']
