(function (Translator) {
    // fr
    Translator.add("alert.page.created", "Page cr\u00e9\u00e9e", "messages", "fr");
    Translator.add("alert.page.deleted", "Page supprim\u00e9e", "messages", "fr");
    Translator.add("alert.page.updated", "Page mise \u00e0 jour", "messages", "fr");
    Translator.add("alert.post.created", "Article cr\u00e9\u00e9", "messages", "fr");
    Translator.add("alert.post.deleted", "Article supprim\u00e9", "messages", "fr");
    Translator.add("alert.post.updated", "Article mis \u00e0 jour", "messages", "fr");
    Translator.add("alert.field.required", "Ce champ est obligatoire.", "messages", "fr");
    Translator.add("alert.field.date", "Cette n'est pas valide", "messages", "fr");
    Translator.add("button.add.global", "Ajouter", "messages", "fr");
    Translator.add("button.back.site", "Retour au site", "messages", "fr");
    Translator.add("button.cancel.global", "Annuler", "messages", "fr");
    Translator.add("button.save.global", "Enregistrer", "messages", "fr");
    Translator.add("button.save_quit.global", "Enregistrer & Fermer", "messages", "fr");
    Translator.add("button.search.global", "Rechercher", "messages", "fr");
    Translator.add("error.important", "Une erreur importante est survenue", "messages", "fr");
    Translator.add("error.not_found", "La page demand\u00e9e n'existe pas", "messages", "fr");
    Translator.add("form.post.category", "Categorie", "messages", "fr");
    Translator.add("form.publication.date_publication_begin", "Date de publication", "messages", "fr");
    Translator.add("form.publication.date_publication_end", "Date de fin", "messages", "fr");
    Translator.add("form.publication.date_add", "Cr\u00e9ation", "messages", "fr");
    Translator.add("form.publication.date_update", "Modification", "messages", "fr");
    Translator.add("form.publication.is_highlighted", "Affich\u00e9 sur la home", "messages", "fr");
    Translator.add("global.content", "Contenu", "messages", "fr");
    Translator.add("global.frontend", "Frontend", "messages", "fr");
    Translator.add("global.label", "Libell\u00e9 du menu", "messages", "fr");
    Translator.add("global.meta_description", "Meta description", "messages", "fr");
    Translator.add("global.no", "Non", "messages", "fr");
    Translator.add("global.page", "Page", "messages", "fr");
    Translator.add("global.path", "Chemin", "messages", "fr");
    Translator.add("global.post", "Article", "messages", "fr");
    Translator.add("global.rollover", "Texte en rollover", "messages", "fr");
    Translator.add("global.status", "Status", "messages", "fr");
    Translator.add("global.subtitle", "Sous-titre", "messages", "fr");
    Translator.add("global.title", "Titre", "messages", "fr");
    Translator.add("global.yes", "Oui", "messages", "fr");
    Translator.add("header.creation.page", "Cr\u00e9ation de page", "messages", "fr");
    Translator.add("header.creation.post", "Cr\u00e9ation d'article", "messages", "fr");
    Translator.add("header.edition", "Edition de \"%page%\"", "messages", "fr");
    Translator.add("header.publication_setting", "Param\u00e8tres de publication", "messages", "fr");
    Translator.add("menu.header", "BackOffice", "messages", "fr");
    Translator.add("menu.page", "Page", "messages", "fr");
    Translator.add("menu.pages", "Pages", "messages", "fr");
    Translator.add("menu.posts", "Articles", "messages", "fr");
    Translator.add("message.confirm.delete_page", "Confirmez-vous la suppression de la page \"%page%\"", "messages", "fr");
    Translator.add("message.confirm.delete_post", "Confirmez-vous la suppression de l'article \"%post%\"", "messages", "fr");
    Translator.add("message.confirm.leave_change", "Les donn\u00e9es non sauvegard\u00e9es seront perdues, continuer ?", "messages", "fr");
    Translator.add("over.path", "Le chemin doit \u00eatre en minuscule et ne contenir ni accent, ni espace", "messages", "fr");
    Translator.add("placeholder.menu_name", "Libell\u00e9 du menu", "messages", "fr");
    Translator.add("placeholder.path", "chemin\/sans_espace\/ni_accent", "messages", "fr");
    Translator.add("placeholder.rollover", "Texte au survol", "messages", "fr");
    Translator.add("placeholder.search.global", "Recherche globale", "messages", "fr");
    Translator.add("placeholder.subtitle", "Sous-titre", "messages", "fr");
    Translator.add("placeholder.title", "Titre", "messages", "fr");
    Translator.add("post.category.all", "Toutes", "messages", "fr");
    Translator.add("post.category.news", "Nouvelles", "messages", "fr");
    Translator.add("post.category.testimonial", "Testimoniale", "messages", "fr");
    Translator.add("post.category.video", "Vid\u00e9o", "messages", "fr");
    Translator.add("post.category.zoom", "Zoom", "messages", "fr");
    Translator.add("publication_status.status.archived", "Archiv\u00e9", "messages", "fr");
    Translator.add("publication_status.status.published", "Publi\u00e9", "messages", "fr");
    Translator.add("publication_status.status.unpublished", "Non publi\u00e9", "messages", "fr");
    Translator.add("publication_status.status.published_unpublished", "Publi\u00e9s et non", "messages", "fr");
})(Translator);
